
package com.jyoti.ws.clientTopDown;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FlightBookingService_topDownService", targetNamespace = "http://ws.bookingservice.jyoti.com/", wsdlLocation = "http://localhost:8000/?wsdl")
public class FlightBookingServiceTopDownService
    extends Service
{

    private final static URL FLIGHTBOOKINGSERVICETOPDOWNSERVICE_WSDL_LOCATION;
    private final static WebServiceException FLIGHTBOOKINGSERVICETOPDOWNSERVICE_EXCEPTION;
    private final static QName FLIGHTBOOKINGSERVICETOPDOWNSERVICE_QNAME = new QName("http://ws.bookingservice.jyoti.com/", "FlightBookingService_topDownService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8000/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FLIGHTBOOKINGSERVICETOPDOWNSERVICE_WSDL_LOCATION = url;
        FLIGHTBOOKINGSERVICETOPDOWNSERVICE_EXCEPTION = e;
    }

    public FlightBookingServiceTopDownService() {
        super(__getWsdlLocation(), FLIGHTBOOKINGSERVICETOPDOWNSERVICE_QNAME);
    }

    public FlightBookingServiceTopDownService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FLIGHTBOOKINGSERVICETOPDOWNSERVICE_QNAME, features);
    }

    public FlightBookingServiceTopDownService(URL wsdlLocation) {
        super(wsdlLocation, FLIGHTBOOKINGSERVICETOPDOWNSERVICE_QNAME);
    }

    public FlightBookingServiceTopDownService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FLIGHTBOOKINGSERVICETOPDOWNSERVICE_QNAME, features);
    }

    public FlightBookingServiceTopDownService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FlightBookingServiceTopDownService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FlightBookingServiceTopDown
     */
    @WebEndpoint(name = "FlightBookingService_topDownPort")
    public FlightBookingServiceTopDown getFlightBookingServiceTopDownPort() {
        return super.getPort(new QName("http://ws.bookingservice.jyoti.com/", "FlightBookingService_topDownPort"), FlightBookingServiceTopDown.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FlightBookingServiceTopDown
     */
    @WebEndpoint(name = "FlightBookingService_topDownPort")
    public FlightBookingServiceTopDown getFlightBookingServiceTopDownPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.bookingservice.jyoti.com/", "FlightBookingService_topDownPort"), FlightBookingServiceTopDown.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FLIGHTBOOKINGSERVICETOPDOWNSERVICE_EXCEPTION!= null) {
            throw FLIGHTBOOKINGSERVICETOPDOWNSERVICE_EXCEPTION;
        }
        return FLIGHTBOOKINGSERVICETOPDOWNSERVICE_WSDL_LOCATION;
    }

}
